Numpy operation

In [2]:
import numpy as np
import math
import time

In [26]:
a = np.arange(10)

In [27]:
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [28]:
c = a[1:7:2]
b = a[-1:]
print(c)
print(b)

[1 3 5]
[9]


In [29]:
a = np.array([1,3,4,5,6,7,2])
b = -a 
b = b+1
c = np.sum(b)
d = np.mean(a)
e = a**2
print(e)

[ 1  9 16 25 36 49  4]


In [30]:
def my_dot(a,b):
    x = 0 
    for i in range(a.shape[0]):
        x = x + a[i]*b[i]
    return x    

In [31]:
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])
print(f"my_dot(a, b) = {my_dot(a, b)}")

my_dot(a, b) = 24


In [32]:
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])
c = np.dot(a, b)
print(f"NumPy 1-D np.dot(a, b) = {c}, np.dot(a, b).shape = {c.shape} ") 
c = np.dot(b, a)
print(f"NumPy 1-D np.dot(b, a) = {c}, np.dot(a, b).shape = {c.shape} ")

NumPy 1-D np.dot(a, b) = 24, np.dot(a, b).shape = () 
NumPy 1-D np.dot(b, a) = 24, np.dot(a, b).shape = () 


In [34]:
np.random.seed(1)
a = np.random.rand(1000)
b = np.random.rand(1000)
t_start = time.time()
c = np.dot(a,b)
t_end = time.time()

print(f"np.dot(a, b) =  {c:.4f}")
print(f"Vectorized version duration: {1000*(t_end-t_start):.4f} ms ")

t_start = time.time()
c = np.dot(a,b)
t_end = time.time()

print(f"my_dot(a, b) =  {c:.4f}")
print(f"loop version duration: {1000*(t_end-t_start):.4f} ms ")


np.dot(a, b) =  261.8488
Vectorized version duration: 1.0247 ms 
my_dot(a, b) =  261.8488
loop version duration: 0.0000 ms 


In [35]:
a = np.zeros((1, 5))                                       
print(f"a shape = {a.shape}, a = {a}")                     

a = np.zeros((2, 1))                                                                   
print(f"a shape = {a.shape}, a = {a}") 

a = np.random.random_sample((1, 1))  
print(f"a shape = {a.shape}, a = {a}") 


a shape = (1, 5), a = [[0. 0. 0. 0. 0.]]
a shape = (2, 1), a = [[0.]
 [0.]]
a shape = (1, 1), a = [[0.57697785]]


In [6]:
a = np.array([[1 , 2 ,3],[2,4,5],[3,1,2]])
print(a)
print(a.shape)

[[1 2 3]
 [2 4 5]
 [3 1 2]]
(3, 3)


In [9]:
print("a[:,:] = \n", a[0,:], ",  a[:,:].shape =", a[1,:].shape)

a[:,:] = 
 [1 2 3] ,  a[:,:].shape = (3,)
